version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # ports:
    #   - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "8002:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./backend/app:/app/app
  frontend:
    build: ./frontend
    user: "1000:1000" # 使用指定宿主机用户ID和组ID
    # command: sh -c "tail -f /dev/null"  # 保持容器运行
    ports:
      - "5174:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8002

volumes:
  postgres_data:
