version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8003:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/sqlite:/var/lib/sqlite
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:////var/lib/sqlite/sql_app.db
  frontend:
    build: ./frontend
    user: "1000:1000"
    # command: sh -c "tail -f /dev/null"  # 保持容器运行
    ports:
      - "5174:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8003
